minimumReleaseAge: 1440 # 24 hours

packages:
  - client
  - packages/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
