packages:
  - web
  - packages/*

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 1440 # 24 hours

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - sqlite3
  - unrs-resolver
